### ISSUE TITLE
Consumer key and secret leaked

### ISSUE THREAD

**Issue by adamdecaf** [FiloSottile/HNTitles#3]
See: https://github.com/FiloSottile/HNTitles/blob/master/tweep.py#L12

From: https://twitter.com/vietlq/status/1065930252180811776

**Comment by FiloSottile** [comment]
2013 me believed they were useless without the corresponding secrets, and 2018 me found it plausible enough not to rotate them. Was I wrong?

**Comment by adamdecaf** [comment]
I'm not sure and I'd assume if they were leaked your api account would have been taken over years ago. 

The docs mention you could programmatically retrieve the access key: http://docs.tweepy.org/en/v3.5.0/auth_tutorial.html (at the bottom)

**Comment by FiloSottile** [comment]
I'm going to assume that it's been fine until now and it will keep being fine. It's not a sensitive account anyway. But thanks for the ping!
